#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
DIST.mkdir(parents=True, exist_ok=True)

headers = """# DiamondSignals publish headers
# Generated by scripts/write_netlify_headers.py

/*
  Cache-Control: public,max-age=0,must-revalidate

/*.html
  Cache-Control: public,max-age=0,must-revalidate

/live/*
  Cache-Control: public,max-age=0,must-revalidate

/status/*
  Cache-Control: public,max-age=0,must-revalidate

/*.json
  Cache-Control: public,max-age=0,must-revalidate

/*.js
  Cache-Control: public,max-age=0,must-revalidate

/*.css
  Cache-Control: public,max-age=0,must-revalidate

/dossier_canon.json
  Access-Control-Allow-Origin: https://app.diamondsignals.ai
  Access-Control-Allow-Methods: GET, HEAD, OPTIONS
  Access-Control-Allow-Headers: Content-Type
  Cache-Control: public,max-age=0,must-revalidate

/scout_metrics.json
  Access-Control-Allow-Origin: https://app.diamondsignals.ai
  Access-Control-Allow-Methods: GET, HEAD, OPTIONS
  Access-Control-Allow-Headers: Content-Type
  Cache-Control: public,max-age=0,must-revalidate

/player_index.json
  Access-Control-Allow-Origin: https://app.diamondsignals.ai
  Access-Control-Allow-Methods: GET, HEAD, OPTIONS
  Access-Control-Allow-Headers: Content-Type
  Cache-Control: public,max-age=0,must-revalidate

/admin/player_signal_index.json
  Access-Control-Allow-Origin: https://app.diamondsignals.ai
  Access-Control-Allow-Methods: GET, HEAD, OPTIONS
  Access-Control-Allow-Headers: Content-Type
  Cache-Control: public,max-age=0,must-revalidate
"""

out = DIST / "_headers"
out.write_text(headers, encoding="utf-8")
print(f"Wrote {out}")
print("cache_policy_html_no_stale: true")
print("cache_policy_status_json_no_stale: true")
print("cache_policy_unfingerprinted_assets_no_stale: true")
